### ISSUE TITLE
export.default produces invalid javascript

### ISSUE THREAD

**Issue by gabemeola** [tbranyen/babel-plugin-transform-commonjs#12]
When a module has `export.default = `, this transform creates a variable called `default`. This is invalid because `default` is a reserved word.

Runtime Error: `Uncaught SyntaxError: Unexpected token 'default'`

**test**
```js
const hello = 'hello'

exports.default = hello
```

Sandbox: https://babeljs.io/repl#?babili=false&browsers=&build=&builtIns=false&spec=false&loose=false&code_lz=MYewdgzgLgBAFgUwDZJDAvDA5IlIsBQBCAHgA4gBOUEAdACYIBmAhgK5Kya6pA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=&prettier=false&targets=&version=7.6.0&externalPlugins=babel-plugin-transform-commonjs%401.1.5

**Comment by tbranyen** [comment]
Released in: babel-plugin-transform-commonjs@1.1.6

**Comment by gabemeola** [comment]
🎉 much thanks!
